openapi: 3.0.0
info:
  title: GoLearning API
  description: API documentation for GoLearning
  version: 1.0.0
paths:
  /regis:
    post:
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: rezz
                password:
                  type: string
                  example: admin12345
                email:
                  type: string
                  example: aaaa@gmail.com
      responses:
        '200':
          description: Successful registration
  /login:
    post:
      summary: Login User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: rezz
                password:
                  type: string
                  example: admin12345
      responses:
        '200':
          description: Successful login
  /courses:
    get:
      summary: Get Course
      responses:
        '200':
          description: Successful retrieval of courses
    post:
      summary: Post Course
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_name:
                  type: string
                  example: Pemograman 3
                teacher:
                  type: string
                  example: Budi
      responses:
        '200':
          description: Successful creation of course
  /courses/1:
    put:
      summary: Update Course
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_name:
                  type: string
                  example: Pemograman 3
                teacher:
                  type: string
                  example: Yanto
      responses:
        '200':
          description: Successful update of course
    delete:
      summary: Delete Course
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful deletion of course
  /students:
    get:
      summary: Get Student
      responses:
        '200':
          description: Successful retrieval of students
    post:
      summary: Post Student
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id:
                  type: integer
                  example: 2
                name:
                  type: string
                  example: Reza
                class:
                  type: string
                  example: 2A
                address:
                  type: string
                  example: Bandung
      responses:
        '200':
          description: Successful creation of student
  /students/2:
    put:
      summary: Update Student
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id:
                  type: integer
                  example: 2
                name:
                  type: string
                  example: Fatir
                class:
                  type: string
                  example: 2A
                address:
                  type: string
                  example: Batu
      responses:
        '200':
          description: Successful update of student
    delete:
      summary: Delete Student
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful deletion of student
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
