openapi: 3.0.0
info:
  title: GoLearning
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /mhs714220019/regis:
    post:
      tags:
        - default
      summary: UserRegistration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rezz
                password: admin12345
                email: aaaa@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220019/login:
    post:
      tags:
        - default
      summary: LoginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: was
                password: admin12345
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220019courses:
    get:
      tags:
        - default
      summary: GetCourse
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostCourse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Budiansyah
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220019courses/1:
    put:
      tags:
        - default
      summary: PutCourse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Yanto
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteCourse
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220019students:
    get:
      tags:
        - default
      summary: GetStudent
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostStudent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Reza
                class: 2A
                address: Bandung
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220019students/2:
    put:
      tags:
        - default
      summary: PutStudent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Waskitho
                class: 2A
                address: Batu
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteStudent
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
