openapi: 3.0.0
info:
  title: GoLearning
  version: 1.0.0
servers:
  - url: "https://130.162.195.228/mhs714220019"
components:
  securitySchemes:
    bearerAuth:
      type: https
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: User Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rezz
                password: admin12345
                email: aaaa@gmail.com
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: was
                password: admin12345
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /courses:
    get:
      tags:
        - default
      summary: Get Course
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Post Course
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Budiansyah
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /courses/{id}:
    put:
      tags:
        - default
      summary: Put Course
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_name: Pemograman 3
                teacher: Yanto
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Course
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /students:
    get:
      tags:
        - default
      summary: Get Student
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Post Student
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Reza
                class: 2A
                address: Bandung
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /students/{id}:
    put:
      tags:
        - default
      summary: Put Student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                course_id: 2
                name: Waskitho
                class: 2A
                address: Batu
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
